/**
 * Enumeration of user roles available in the system.
 *
 * This enum defines the single supported role: 'member'. The Todo List
 * application supports exactly one user role to maintain simplicity and enforce
 * strict data ownership.
 *
 * No other roles are allowed (e.g., admin, guest). All users are members, and
 * all member data is isolated and private. Role assignment is stored in the
 * todo_list_member_roles table and linked to each member via
 * todo_list_member_id.
 *
 * This enum ensures type safety and consistency when roles are referenced
 * across the system. The value 'member' must match exactly as defined in the
 * todo_list_member_roles table's role_name column.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ETodoListMemberRole = "member";
