import { IPage } from "./IPage";
import { ITodoListTodoListTask } from "./ITodoListTodoListTask";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoListTodoListTask = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ITodoListTodoListTask[];
};
